version: '3.7'

services:
  caddy-gateway:
    image: caddy-gateway
    build: .
    volumes:
      - type: bind
        source: ./Caddyfile
        target: /caddy/Caddyfile
      - ./.caddy:/caddy/.caddy
    ports:
      - 2019:2019
      - 80:80
      - 443:443
