version: '3.7'

services:
  caddy-gateway:
    image: caddy-gateway
    container_name: caddy-gateway
    build: .
    volumes:
      - type: bind
        source: ./Caddyfile
        target: /caddy/Caddyfile
      - ./.caddy:/root/.caddy
    ports:
      - 2019:2019
      - 80:80
      - 443:443

networks:
  default:
    name: 0x1c-net